### ISSUE TITLE
Can't merge models anymore

### ISSUE THREAD

**Issue by DavideAlidosi** [wkpark/sd-webui-model-mixer#105]
I have an error when try to merge models:
```
use_extra_elements =  True
 - mm_max_models =  2
*** Error running before_process: L:\WebUI\webui\extensions\sd-webui-model-mixer\scripts\model_mixer.py
    Traceback (most recent call last):
      File "L:\WebUI\webui\modules\scripts.py", line 710, in before_process
        script.before_process(p, *script_args)
      File "L:\WebUI\webui\extensions\sd-webui-model-mixer\scripts\model_mixer.py", line 2793, in before_process
        if type(alpha) == str: alpha = float(alpha)
    ValueError: could not convert string to float: 'Sum'
```
This happening to any operators.
Thanks

**Comment by DavideAlidosi** [comment]
Thank you for checking the problem, after resetting some settings the problem was solved. However, it remains peculiar how the problem came up.
