### ISSUE TITLE
No module named 'hyperactive', Auto Merger seems not work

### ISSUE THREAD

**Issue by A-B-01** [wkpark/sd-webui-model-mixer#110]
Hello, wkpark, your extension is fantastic, but I have a problem here, when I tried testing the "auto merge", it rised an error: 
"No module named 'hyperactive' "

Here follows the log:

 - loading sd_modelmixer.hyper...
 - set search lower, upper = -0.2 0.2
debugs =  ['elemental merge']
use_extra_elements =  True
 - mm_max_models =  3
config hash =  83d0b768e639ffda5bc85c1a9150f07d3264cd3016e4781bdf1de22673da3ed5
  - mm_use [True, False, False]
  - model_a Anything-V3.0-pruned.ckpt [543bcbc212]
  - base_model None
  - max_models 3
  - models ['ayonimix_V6.safetensors']
  - modes ['Sum']
  - calcmodes ['Normal']
  - usembws [['BASE', 'INP*', 'MID', 'OUT*']]
  - weights ['0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5']
  - alpha [0.5]
  - adjust
  - use elemental [False]
  - elementals ['']
  - Parse elemental merge...
model_a = Anything-V3.0-pruned
Loading from file D:\stable-diffusion-webui\models\Stable-diffusion\Anything-V3.0-pruned.ckpt...
isxl = False , sd2 = False
compact_mode =  True
Loading model ayonimix_V6...
Loading from file D:\stable-diffusion-webui\models\Stable-diffusion\ayonimix_V6.safetensors...
Calculating sha256 for D:\stable-diffusion-webui\models\Stable-diffusion\ayonimix_V6.safetensors: f3a242fcaaf1d540a1c2d55602e83766cc2efbdf64c2b70e62518cbf516bfcd3
mode = Sum, mbw mode, alpha = [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5]
Stage #1/3: 100%|████████████████████████████████████████████████████████████████████| 882/882 [02:35<00:00,  5.66it/s]
Check uninitialized #2/3: 100%|███████████████████████████████████████████████████| 882/882 [00:00<00:00, 60660.43it/s]
Save unchanged weights #3/3: 100%|███████████████████████████████████████████████████████████| 937/937 [00:00<?, ?it/s]
Clip is fine
 - merge processing in 215.4s (prepare: 38.7s, merging: 176.7s).
WARN: lowvram/medvram load_model() with minor workaround
Creating model from config: D:\stable-diffusion-webui\configs\v1-inference.yaml
Loading VAE weights specified in settings: D:\stable-diffusion-webui\models\VAE\vae-ft-mse-840000-ema-pruned.vae.pt
Applying attention optimization: xformers... done.
Model loaded in 10.6s (create model: 1.2s, apply weights to model: 2.2s, apply half(): 0.2s, load VAE: 4.4s, load textual inversion embeddings: 0.8s, calculate empty prompt: 1.5s).
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:27<00:00,  1.36s/it]
Total progress: 20it [00:21,  1.06s/it]
Traceback (most recent call last):it/s]
  File "D:\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "D:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "D:\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "D:\stable-diffusion-webui\venv\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "D:\stable-diffusion-webui\extensions\sd-webui-model-mixer\scripts\model_mixer.py", line 2737, in hyper_merge
    ret = hyper.hyper_optimizer(**optimizer_args)
  File "D:\stable-diffusion-webui\extensions\sd-webui-model-mixer\sd_modelmixer\hyper.py", line 351, in hyper_optimizer
    import hyperactive.optimizers
ModuleNotFoundError: No module named 'hyperactive'

**Comment by wkpark** [comment]
this issue was automatically closed by commit 8a0b839
thanks for your reporting!
