### ISSUE TITLE
NameError: name 'orig_set_sed_model' is not defined

### ISSUE THREAD

**Issue by DavideAlidosi** [wkpark/sd-webui-model-mixer#156]
After the last update, when try to merge two models:
```
*** Error running before_process: L:\indrema\webui\extensions\sd-webui-model-mixer\scripts\model_mixer.py
    Traceback (most recent call last):
      File "L:\indrema\webui\modules\scripts.py", line 776, in before_process
        script.before_process(p, *script_args)
      File "L:\indrema\webui\extensions\sd-webui-model-mixer\scripts\model_mixer.py", line 4508, in before_process
        sd_models.load_model(checkpoint_info=checkpoint_info, already_loaded_state_dict=state_dict)
      File "L:\indrema\webui\modules\sd_models.py", line 760, in load_model
        model_data.set_sd_model(sd_model)
      File "L:\indrema\webui\extensions\sd-webui-model-mixer\scripts\model_mixer.py", line 6212, in set_sd_model
        orig_set_sed_model(v, already_loaded)
    NameError: name 'orig_set_sed_model' is not defined

---
*** Error completing request
*** Arguments: ('task(14mfvb5vhv63i8c)', <gradio.routes.Request object at 0x000001FFA8E06920>, '', '', [], 20, 'DPM++ 2M SDE Karras', 1, 1, 7, 680, 544, True, 0.5, 2, '4x_NMKD-Superscale-SP_178000_G', 10, 0, 0, 'Use same checkpoint', 'Use same sampler', '', '', [], 0, False, '', 0.8, -1, False, -1, 0, 0, 0, True, False, 1, False, False, False, 1.1, 1.5, 100, 0.7, False, True, False, False, False, 0, 'AUTOMATIC/promptgen-lexart', '', 3, False, 'Default', 'Default', 1, False, 0, False, 0, 0, 0, 0, 'START:1,1,1,1,0.75,0.5,0.25,0,0,0,0,0,0,0,0,0,0\nMIDDLE:1,0,0,0,0.25,0.5,0.75,1,1,1,1,0.75,0.5,0.25,0,0,0\nEND:1,0,0,0,0,0,0,0,0,0,0,0.25,0.5,0.75,1,1,1\n\nNONE:0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0\nALL:1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1\nINS:1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0\nIND:1,0,0,0,1,1,1,0,0,0,0,0,0,0,0,0,0\nINALL:1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0\nMIDD:1,0,0,0,1,1,1,1,1,1,1,1,0,0,0,0,0\nOUTD:1,0,0,0,0,0,0,0,1,1,1,1,0,0,0,0,0\nOUTS:1,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1\nOUTALL:1,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1\nALL:0.5:0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5', True, 0, 'values', '0,0.25,0.5,0.75,1', 'Block ID', 'IN05-OUT05', 'none', '', '0.5,1', 'BASE,IN00,IN01,IN02,IN03,IN04,IN05,IN06,IN07,IN08,IN09,IN10,IN11,M00,OUT00,OUT01,OUT02,OUT03,OUT04,OUT05,OUT06,OUT07,OUT08,OUT09,OUT10,OUT11', 1.0, 'black', '20', False, 'ATTNDEEPON:IN05-OUT05:attn:1\n\nATTNDEEPOFF:IN05-OUT05:attn:0\n\nPROJDEEPOFF:IN05-OUT05:proj:0\n\nXYZ:::1', False, False, True, 'ultima.safetensors [af9710b394]', 'None', 3, '', {'save_settings': ['fp16', 'prune', 'safetensors'], 'calc_settings': ['GPU', 'fastrebasin']}, True, False, False, 'ultima_real.safetensors [b4c8af69f2]', 'None', 'None', 'Sum', 'Sum', 'Sum', 0.5, 0.5, 0.5, True, True, True, [], [], [], [], [], [], '0.05,0.06,0.1,0.16,0.22,0.26,0.32,0.36,0.4,0.44,0.46,0.48,0.49,0.45,0.49,0.48,0.46,0.44,0.4,0.36,0.32,0.26,0.22,0.16,0.1,0.06', '0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5', '0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5', False, False, False, '', '', '', 'Normal', 'Normal', 'Normal', False, False, 'positive', 'comma', 0, False, False, 'start', '', 1, '', [], 0, '', [], 0, '', [], True, False, False, False, False, False, False, 0, False) {}
    Traceback (most recent call last):
      File "L:\indrema\webui\modules\call_queue.py", line 57, in f
        res = list(func(*args, **kwargs))
      File "L:\indrema\webui\modules\call_queue.py", line 36, in f
        res = func(*args, **kwargs)
      File "L:\indrema\webui\modules\txt2img.py", line 110, in txt2img
        processed = processing.process_images(p)
      File "L:\indrema\webui\modules\processing.py", line 772, in process_images
        sd_models.reload_model_weights()
      File "L:\indrema\webui\modules\sd_models.py", line 858, in reload_model_weights
        sd_model = reuse_model_from_already_loaded(sd_model, checkpoint_info, timer)
      File "L:\indrema\webui\extensions\sd-webui-model-mixer\scripts\model_mixer.py", line 6187, in hook_reuse_model_from_already_loaded
        ret = orig_reuse_model_from_already_loaded(sd_model, checkpoint_info, timer)
      File "L:\indrema\webui\modules\sd_models.py", line 811, in reuse_model_from_already_loaded
        model_data.set_sd_model(already_loaded, already_loaded=True)
      File "L:\indrema\webui\extensions\sd-webui-model-mixer\scripts\model_mixer.py", line 6212, in set_sd_model
        orig_set_sed_model(v, already_loaded)
    NameError: name 'orig_set_sed_model' is not defined
```

**Comment by wkpark** [comment]
fixed by https://github.com/wkpark/sd-webui-model-mixer/commit/36b25aba48c0f0b3172640f677e264b08973a1c1

thank you for your reporting!

**Comment by DavideAlidosi** [comment]
Thanks for fast fixing, now work fine.
