### ISSUE TITLE
denoiser.sigmas KeyError

### ISSUE THREAD

**Issue by Neytiri7** [wkpark/sd-webui-model-mixer#159]
![Screenshot 2024-07-17 at 01 57 24](https://github.com/user-attachments/assets/85df4584-c99f-4dfc-a6f4-10cb5c24cf0e)

*** Error running before_process: A:\SynologyDrive\stable-diffusion-webui-Scenery\extensions\sd-webui-model-mixer\scripts\model_mixer.py
    Traceback (most recent call last):
      File "A:\SynologyDrive\stable-diffusion-webui-Scenery\modules\scripts.py", line 817, in before_process
        script.before_process(p, *script_args)
      File "A:\SynologyDrive\stable-diffusion-webui-Scenery\extensions\sd-webui-model-mixer\scripts\model_mixer.py", line 4130, in before_process
        del theta_1[key]
    KeyError: 'denoiser.sigmas'

**Comment by Neytiri7** [comment]
It works fine.
Thank you.
