### ISSUE TITLE
Error when try to bake a VAE 

### ISSUE THREAD

**Issue by DavideAlidosi** [wkpark/sd-webui-model-mixer#45]
```
Baking in VAE from L:\A1111 Portable\sd.webui\webui\models\VAE\vae-ft-mse-840000-ema-pruned.safetensors
Bake in VAE...:   0%|                                                                          | 0/248 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "L:\A1111 Portable\sd.webui\system\python\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "L:\A1111 Portable\sd.webui\system\python\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "L:\A1111 Portable\sd.webui\system\python\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "L:\A1111 Portable\sd.webui\system\python\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "L:\A1111 Portable\sd.webui\system\python\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "L:\A1111 Portable\sd.webui\system\python\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "L:\A1111 Portable\sd.webui\system\python\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "L:\A1111 Portable\sd.webui\webui\extensions\sd-webui-model-mixer\scripts\model_mixer.py", line 2561, in save_current_model
    state_dict[key_name] = copy.deepcopy(vae_dict[key])
AttributeError: 'function' object has no attribute 'deepcopy'
```
Thanks for check it.

**Comment by wkpark** [comment]
thank you for your reporting!

**Comment by DavideAlidosi** [comment]
Thanks a lot for fix it so qulickly, there's no problem now!

There is any possibility to add a LoRA merger like the supermerger one?

**Comment by wkpark** [comment]
> Thanks a lot for fix it so qulickly, there's no problem now!
> 
> There is any possibility to add a LoRA merger like the supermerger one?

There are no plans at the moment.
will consider it once the model-mixer functionality is more stabilised.

**Comment by wkpark** [comment]
initial LoRA/LyCORIS export support added at PR #51

**Comment by DavideAlidosi** [comment]
Thanks a lot, work like charm.
