### ISSUE TITLE
This extension now breaks A1111 WebUI with --no-gradio-queue enabled

### ISSUE THREAD

**Issue by Gushousekai195** [wkpark/sd-webui-model-mixer#80]
I installed this extension and now I am unable to use Automatic1111's webui unless I don't enable the --no-gradio-queue flag. But doing so causes my console output to be flooded with HTTP POST messages. It clutters up the output.

The error is as follows:

```
Traceback (most recent call last):
  File "D:\AI\stable-diffusion-webui\launch.py", line 48, in <module>
    main()
  File "D:\AI\stable-diffusion-webui\launch.py", line 44, in main
    start()
  File "D:\AI\stable-diffusion-webui\modules\launch_utils.py", line 436, in start
    webui.webui()
  File "D:\AI\stable-diffusion-webui\webui.py", line 79, in webui
    app, local_url, share_url = shared.demo.launch(
  File "D:\AI\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1858, in launch
    self.validate_queue_settings()
  File "D:\AI\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1690, in validate_queue_settings
    raise ValueError("Progress tracking requires queuing to be enabled.")
ValueError: Progress tracking requires queuing to be enabled.
```

Is disabling the queue really necessary?

**Comment by wkpark** [comment]
thank you for your feedback.

will check `--no-gradio-queue` related soon
